version: '3.5'


services:


  broker1:
    image: confluentinc/cp-kafka:7.2.1
    container_name: broker1
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker1:9092,CONTROLLER://broker1:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker1:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
    volumes:
      - ./setup.sh:/tmp/setup.sh
    command: "bash -c '/tmp/setup.sh && /etc/confluent/docker/run'"
 
  broker2:
    image: confluentinc/cp-kafka:7.2.1
    container_name: broker2
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker2:9092,CONTROLLER://broker2:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker2:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
    volumes:
      - ./setup.sh:/tmp/setup.sh
    command: "bash -c '/tmp/setup.sh && /etc/confluent/docker/run'"
  
  broker3:
    image: confluentinc/cp-kafka:7.2.1
    container_name: broker3
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://broker3:9092,CONTROLLER://broker3:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker3:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker1:9093,2@broker2:9093,3@broker3:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
    volumes:
      - ./setup.sh:/tmp/setup.sh
    command: "bash -c '/tmp/setup.sh && /etc/confluent/docker/run'"